### ISSUE TITLE
Feature request: Random delay added to each keystroke

### ISSUE THREAD

**Issue by fiq** [i-can-not-program/faketyping#2]
How about a random delay added to each fake keystroke. This would make it appear more real when simulating a typing scenario?

**Comment by i-can-not-program** [comment]
Should this also have a chance of making the delay shorter?

**Comment by fiq** [comment]
That would be great!

**Comment by i-can-not-program** [comment]
Fixed with f0c767d

**Comment by i-can-not-program** [comment]
Tell me if anything is wrong with this implementation
